name = "cc-quick-test"
compatibility_date = "2025-06-01"
compatibility_flags = [ "nodejs_compat" ]

main = "./.output/server/index.mjs"
route = "cc-quick-test.pages.dev/*"
pages_build_output_dir = "./dist"

[env.production.vars]
NODE_ENV = "production"

rules = [
  { type = "ESModule", globs = ["**/*.js", "**/*.mjs"]},
]

[site]
bucket = ".output/public"